//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package sandboxapi

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/api/networking/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxEgress) DeepCopyInto(out *SandboxEgress) {
	*out = *in
	if in.Allow != nil {
		in, out := &in.Allow, &out.Allow
		*out = make([]SandboxEgressRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxEgress.
func (in *SandboxEgress) DeepCopy() *SandboxEgress {
	if in == nil {
		return nil
	}
	out := new(SandboxEgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxEgressPort) DeepCopyInto(out *SandboxEgressPort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxEgressPort.
func (in *SandboxEgressPort) DeepCopy() *SandboxEgressPort {
	if in == nil {
		return nil
	}
	out := new(SandboxEgressPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxEgressRule) DeepCopyInto(out *SandboxEgressRule) {
	*out = *in
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(SandboxEgressService)
		**out = **in
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]SandboxEgressPort, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxEgressRule.
func (in *SandboxEgressRule) DeepCopy() *SandboxEgressRule {
	if in == nil {
		return nil
	}
	out := new(SandboxEgressRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxEgressService) DeepCopyInto(out *SandboxEgressService) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxEgressService.
func (in *SandboxEgressService) DeepCopy() *SandboxEgressService {
	if in == nil {
		return nil
	}
	out := new(SandboxEgressService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxIngress) DeepCopyInto(out *SandboxIngress) {
	*out = *in
	if in.From != nil {
		in, out := &in.From, &out.From
		*out = make([]v1.NetworkPolicyPeer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxIngress.
func (in *SandboxIngress) DeepCopy() *SandboxIngress {
	if in == nil {
		return nil
	}
	out := new(SandboxIngress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxModel) DeepCopyInto(out *SandboxModel) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxModel.
func (in *SandboxModel) DeepCopy() *SandboxModel {
	if in == nil {
		return nil
	}
	out := new(SandboxModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxNetwork) DeepCopyInto(out *SandboxNetwork) {
	*out = *in
	if in.Egress != nil {
		in, out := &in.Egress, &out.Egress
		*out = new(SandboxEgress)
		(*in).DeepCopyInto(*out)
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]SandboxPort, len(*in))
		copy(*out, *in)
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(SandboxIngress)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxNetwork.
func (in *SandboxNetwork) DeepCopy() *SandboxNetwork {
	if in == nil {
		return nil
	}
	out := new(SandboxNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxPodMetadata) DeepCopyInto(out *SandboxPodMetadata) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxPodMetadata.
func (in *SandboxPodMetadata) DeepCopy() *SandboxPodMetadata {
	if in == nil {
		return nil
	}
	out := new(SandboxPodMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxPort) DeepCopyInto(out *SandboxPort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxPort.
func (in *SandboxPort) DeepCopy() *SandboxPort {
	if in == nil {
		return nil
	}
	out := new(SandboxPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxSecretFile) DeepCopyInto(out *SandboxSecretFile) {
	*out = *in
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SandboxSecretFileItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxSecretFile.
func (in *SandboxSecretFile) DeepCopy() *SandboxSecretFile {
	if in == nil {
		return nil
	}
	out := new(SandboxSecretFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxSecretFileItem) DeepCopyInto(out *SandboxSecretFileItem) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxSecretFileItem.
func (in *SandboxSecretFileItem) DeepCopy() *SandboxSecretFileItem {
	if in == nil {
		return nil
	}
	out := new(SandboxSecretFileItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretObjectReference) DeepCopyInto(out *SecretObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretObjectReference.
func (in *SecretObjectReference) DeepCopy() *SecretObjectReference {
	if in == nil {
		return nil
	}
	out := new(SecretObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSandbox) DeepCopyInto(out *SwiftSandbox) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSandbox.
func (in *SwiftSandbox) DeepCopy() *SwiftSandbox {
	if in == nil {
		return nil
	}
	out := new(SwiftSandbox)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftSandbox) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSandboxList) DeepCopyInto(out *SwiftSandboxList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwiftSandbox, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSandboxList.
func (in *SwiftSandboxList) DeepCopy() *SwiftSandboxList {
	if in == nil {
		return nil
	}
	out := new(SwiftSandboxList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftSandboxList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSandboxPool) DeepCopyInto(out *SwiftSandboxPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSandboxPool.
func (in *SwiftSandboxPool) DeepCopy() *SwiftSandboxPool {
	if in == nil {
		return nil
	}
	out := new(SwiftSandboxPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftSandboxPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSandboxPoolList) DeepCopyInto(out *SwiftSandboxPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwiftSandboxPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSandboxPoolList.
func (in *SwiftSandboxPoolList) DeepCopy() *SwiftSandboxPoolList {
	if in == nil {
		return nil
	}
	out := new(SwiftSandboxPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftSandboxPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSandboxPoolSpec) DeepCopyInto(out *SwiftSandboxPoolSpec) {
	*out = *in
	if in.VerifyKeySecretRef != nil {
		in, out := &in.VerifyKeySecretRef, &out.VerifyKeySecretRef
		*out = new(SecretObjectReference)
		**out = **in
	}
	out.Memory = in.Memory.DeepCopy()
	in.Network.DeepCopyInto(&out.Network)
	if in.KernelProfileRef != nil {
		in, out := &in.KernelProfileRef, &out.KernelProfileRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.GPUProfileRef != nil {
		in, out := &in.GPUProfileRef, &out.GPUProfileRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(SandboxModel)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSandboxPoolSpec.
func (in *SwiftSandboxPoolSpec) DeepCopy() *SwiftSandboxPoolSpec {
	if in == nil {
		return nil
	}
	out := new(SwiftSandboxPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSandboxSpec) DeepCopyInto(out *SwiftSandboxSpec) {
	*out = *in
	if in.VerifyKeySecretRef != nil {
		in, out := &in.VerifyKeySecretRef, &out.VerifyKeySecretRef
		*out = new(SecretObjectReference)
		**out = **in
	}
	out.Memory = in.Memory.DeepCopy()
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SecretFiles != nil {
		in, out := &in.SecretFiles, &out.SecretFiles
		*out = make([]SandboxSecretFile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Network.DeepCopyInto(&out.Network)
	if in.KernelProfileRef != nil {
		in, out := &in.KernelProfileRef, &out.KernelProfileRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PoolRef != nil {
		in, out := &in.PoolRef, &out.PoolRef
		*out = new(corev1.LocalObjectReference)
		**out = **in
	}
	if in.PodMetadata != nil {
		in, out := &in.PodMetadata, &out.PodMetadata
		*out = new(SandboxPodMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadinessProbe != nil {
		in, out := &in.ReadinessProbe, &out.ReadinessProbe
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSandboxSpec.
func (in *SwiftSandboxSpec) DeepCopy() *SwiftSandboxSpec {
	if in == nil {
		return nil
	}
	out := new(SwiftSandboxSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSandboxStatus) DeepCopyInto(out *SwiftSandboxStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSandboxStatus.
func (in *SwiftSandboxStatus) DeepCopy() *SwiftSandboxStatus {
	if in == nil {
		return nil
	}
	out := new(SwiftSandboxStatus)
	in.DeepCopyInto(out)
	return out
}
