version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule: {interval: weekly}
    groups:
      kubernetes:
        patterns: ["k8s.io/*", "sigs.k8s.io/*"]
  - package-ecosystem: github-actions
    directory: /
    schedule: {interval: weekly}
  - package-ecosystem: docker
    directories: ["/", "/runtime"]
    schedule: {interval: weekly}
  - package-ecosystem: cargo
    directory: /examples
    schedule: {interval: weekly}
