[workspace]
resolver = "2"
members = [
    "hello-http",
    "request-info",
    "outbound-http",
    "key-value",
    "serverless-ai",
    "experimental/mcp",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.94"
license = "Apache-2.0"
publish = false

[workspace.dependencies]
anyhow = "1"
spin-sdk = "=7.0.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
opt-level = "s"
lto = true
strip = true
codegen-units = 1
